---
- name: Installing Minikube
  hosts: localhost
  become: true
  gather_facts: false
  vars:
    executable: "/usr/local/bin/minikube"
    minikube_file: "minikube-linux-amd64"
    temp_dir: "/tmp/"

  tasks:  
    - name: Pulling minikube binary
      get_url:
        url: "https://storage.googleapis.com/minikube/releases/latest/{{ minikube_file }}"
        dest: "{{ temp_dir }}"
        mode: 0755

    - name: Installing binary
      shell:
        cmd: "install {{temp_dir}}{{ minikube_file }} {{executable}}"

    - name: Set default driver as Docker
      shell:
        cmd: "minikube config set driver docker"
    
    - name: Starting minikube
      debug:
        msg: "Start minikube by running: minikube start"
