---
- name: Installing neovim and configuring it
  hosts: localhost
  gather_facts: true
  vars:
    repo: "https://github.com/neovim/neovim"

    # Folders
    config_dest: "{{ ansible_env.HOME }}/.config/"
    download_dest: "/tmp/nvim"
    build_dest: "{{ download_dest }}/build"

  tasks:
    - name: Downloading neovim from github
      git:
        repo: "{{ repo }}"
        dest: "{{ download_dest }}"
        accept_hostkey: true
        clone: true
        version: stable

    - name: Set make command
      command:
        cmd: "make CMAKE_BUILD_TYPE=RelWithDebInfo"
        chdir: "{{ download_dest }}"

    - name: Cpacking deb package
      command:
        cmd: cpack -G DEB
        chdir: "{{ build_dest }}"

    - name: Installing neovim deb package
      become: true
      shell:
        cmd: dpkg -i *.deb
        chdir: "{{ build_dest }}"

    # Download my config from Github
    # - name: Creating configuration folder for neovim
    #   become: false
    #   file:
    #     path: "{{ config_dest }}"
    #     state: directory
    #     mode: 0755

    # - name: Downloading neovim configuration files
    #   become: false
    #   git:
    #     repo: "{{ config_repo }}"
    #     dest: "{{ download_dest }}"
    #     key_file: "{{ ssh_key }}"
    #     accept_hostkey: true

    # - name: Copying neovim configuration files
    #   copy:
    #     src: "{{ download_dest }}"
    #     dest: "{{ config_dest }}"
    #     owner: "{{ ansible_env.USER }}"
    #     group: "{{ ansible_env.USER }}"
    #     mode: 0755

    # - name: Delete "/Downloads/nvim" folder
    #   become: false
    #   file:
    #     path: "{{ download_dest }}"
    #     state: absent

    # - name: Change nvim folder permissions
    #   shell:
    #     cmd: "chown -R {{ user }}:{{ ansible_env.USER }} {{ config_dest }}"
