
---
- name: Installing nvm in fish shell
  hosts: localhost
  gather_facts: no

  tasks:  
    - name: Installing NVM itself
      shell:
        cmd: "curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.31.4/install.sh | bash"

    - name: Check if OMF is installed
      shell:
        cmd: "omf -v"
        executable: /bin/fish
      register: omf_installed
      failed_when: omf_installed.rc != 0

    - name: Install nvm wrapper using OMF
      shell:
        cmd: "omf install nvm"
        executable: /bin/fish