---
- name: Installing main packages on Ubuntu
  hosts: all
  become_method: sudo
  become: true
  gather_facts: false

  tasks:
    - name: Updating apt cache
      apt:
        upgrade: yes
        update_cache: yes
    - name: Check if nala is installed
      stat:
        path: /usr/bin/nala
      register: nala_installed

    - name: Action needed to completetly configure Nala
      become: false
      debug:
        msg: "Run: 'nala fetch' to set up Nala's mirrors."
      when: nala_installed.stat.exists == False

    - name: Installing packages from Ubuntu repository using Nala
      package:
        name: "{{ item }}"
        state: present
      loop:
        - curl
        - net-tools
        - unzip
        - bat
        - yamllint
        - eza
        - nala
        - xdotool
        - yadm
        - fzf

        # Gnome configuration
        - gnome-tweaks
        - gnome-shell-extensions

        # Dev stuff
        - npm
        - nodejs
        - git

        # Used by nvim
        - ripgrep
        - fd-find

        # Build from source
        - ninja-build
        - cmake
        - gettext
      when: nala_installed.stat.exists == True

    - name: Installing Snap packages
      snap:
        name: "{{ item }}"
      loop:
        - vlc
        - multipass
        - lxd
        - jump
        - pinta
        - snap
        - localsend
