#cloud-config
timezone: Europe/Berlin
write_files:
- path: /etc/netplan/99-custom.yaml
  content: |
    network:
      ethernets:
        extra0:
            dhcp4: no
            match:
                macaddress: "52:54:00:4b:ab:cd"
            addresses: [10.13.31.13/24]
      version: 2

runcmd:
  - netplan apply
  - apt update

users:
- default
- name: "daniel"
  sudo: ALL=(ALL) NOPASSWD:ALL
ssh_authorized_keys:
  - "ssh-rsa ### daniel"
