matches:
  - trigger: ":espanso"
    replace: "Hi there!"

  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"

  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo 'Hello from your shell'"

  - trigger: ":mr1"
    replace: "Hey team, can you please review this, when you have a chance? 🕵️"

  - trigger: ":mr2"
    replace: "Hey team, please take a look at this MR when possible 🔎"

  - trigger: ":mr3"
    replace: "Hey team, please take some time to review this MR 🙂"
