---
- name: Install Bitwarden AppImage
  hosts: localhost
  gather_facts: true

  vars:
    bitwarden_url: "https://vault.bitwarden.com/download/?app=desktop&platform=linux"
    appimage_name: "Bitwarden.AppImage"
    desktop_entry: "{{ ansible_user_dir }}/.local/share/applications/bitwarden.desktop"

  tasks:
    - name: Download Bitwarden AppImage
      get_url:
        url: "{{ bitwarden_url }}"
        dest: "{{ ansible_env.HOME }}/Downloads/{{ appimage_name }}"
        mode: "0755"

    - name: Ensure the AppImage is executable
      become: true
      file:
        path: "{{ ansible_env.HOME }}/Downloads/{{ appimage_name }}"
        mode: "0755"
        state: file

    - name: Create desktop entry for Bitwarden
      become: true
      copy:
        dest: "{{ desktop_entry }}"
        content: |
          [Desktop Entry]
          Name=Bitwarden
          Exec={{ ansible_env.HOME }}/Downloads/{{ appimage_name }}
          Icon=bitwarden
          Type=Application
          Categories=Utility;
          Terminal=false
