---
- name: Installing Brave explorer from source
  hosts: all
  become: true
  become_method: ansible.builtin.sudo
  gather_facts: false

  tasks:
    - name: Downloading keyrings from official Brave repository
      get_url:
        url: "https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg"
        dest: "/usr/share/keyrings/brave-browser-archive-keyring.gpg"
        mode: "0444"

    - name: Add Brave repository
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg] https://brave-browser-apt-release.s3.brave.com/ stable main"
        filename: brave-browser-release
        state: present
      become: true

    - name: Updating apt cache
      apt:
        #upgrade: true
        update_cache: true

    - name: Installing Brave browser
      apt:
        name: brave-browser
        state: present
