---
- name: Installing Copilot for Neovim
  hosts: all
  vars:
    config_dest: "{{ ansible_env.HOME }}/.config/nvim/pack/github/start/copilot.vim"
    temp_folder: "/tmp/lazyvim"
    repo: "https://github.com/github/copilot.vim.git"

  tasks:  
    - name: Downloading copilot from github
      git:
        repo: "{{ repo }}"
        dest: "{{ temp_folder }}"
        accept_hostkey: true

    - name: Copying Copilot to "{{ config_dest }}"
      become: true
      copy:
        src: "{{ temp_folder }}/"
        dest: "{{ config_dest }}"
        owner: "{{ ansible_env.USER }}"
        group: "{{ ansible_env.USER }}"
        force: yes
        mode: 0744

    - name: Setup Copilot
      command:
        cmd: "nvim -c Copilot setup"
