---
- name: Creating multipass configuration file
  hosts: all
  vars:
    # Paths
    - ssh_key_path: "{{ ansible_env.HOME }}/.ssh/multipass-ssh-key"
    - ssh_key_path_pub: "{{ ssh_key_path }}.pub"
    - config_path: "{{ ansible_env.HOME }}/automation/config"
    - config_file: "{{ config_path }}/cloud-init.yaml"

  tasks:
    - name: Check if ssh key exists
      stat:
        path: "{{ ssh_key_path }}"
      register: ssh_key_stat

    - name: Create ssh key
      shell: ssh-keygen -t rsa -C "{{ ansible_env.USER }}" -f "{{ ssh_key_path }}"
      when: ssh_key_stat.stat.exists == False

    - name: Check if multipass configuration exists
      stat:
        path: "{{ config_file }}"
      register: multipass_config_stat

    - name: Create multipass configuration directory
      file:
        path: "{{ config_path }}"
        state: directory
      when: multipass_config_stat.stat.exists == False

    # cloud init configuration
    - name: Create multipass configuration
      copy:
        force: yes
        content: |
          #cloud-config
          timezone: Europe/Berlin
          write_files:
          - path: /etc/netplan/99-custom.yaml
            content: |
              network:
                ethernets:
                  extra0:
                      dhcp4: no
                      match:
                          macaddress: "52:54:00:4b:ab:cd"
                      addresses: [10.13.31.13/24]
                version: 2

          runcmd:
            - apt update
            - netplan apply

          users:
          - default
          - name: ubuntu
            sudo: ALL=(ALL) NOPASSWD:ALL
          ssh_authorized_keys:
            - "{{ lookup('file', ssh_key_path_pub) }}"

        dest: "{{ config_file }}"
