---
# Scheduling CronJob to update Automation repository
# This playbook will create a ssh key, add it to ssh agent and schedule a cronjob to update the automation repository
# You need to add the "github_cronjob" key to your github account

- name: Scheduling CronJob to update Automation repository
  hosts: all
  vars:
    # Schedule
    minute: "30"
    hour: "10"
    day: "*"
    month: "*"
    weekday: "*"

    # Paths
    home: "{{ ansible_env.HOME }}"
    ssh_key_path: "{{ ansible_env.HOME }}/.ssh/github_cronjob"

  tasks:
    - name: Check if ssh key exists
      stat:
        path: "{{ ssh_key_path }}"
      register: ssh_key_stat

    - name: Create ssh key
      shell: ssh-keygen -t rsa -C "{{ ansible_env.USER }}" -f "{{ ssh_key_path }}"
      when: ssh_key_stat.stat.exists == False

    - name: Add to ssh agent
      shell: eval "$(ssh-agent -s)"
      when: ssh_key_stat.stat.exists == False

    - name: Add ssh key to ssh agent
      shell: ssh-add "{{ ssh_key_path }}"
      when: ssh_key_stat.stat.exists == False

    - name: "Schedule at: Weekdays: {{ weekday }}, Time: {{ hour }}:{{ minute }}}"
      cron:
        name: "automation_update"
        state: present
        minute: "{{ minute }}"
        hour: "{{ hour }}"
        day: "{{ day }}"
        month: "{{ month }}"
        weekday: "{{ weekday }}"
        job: "bash {{ home }}/automation/push-to-github-script.sh {{ home }}/automation/ >> {{ home }}/system/logs/ansiblecron.log 2>&1"
