---
- name: Installing fish shell
  hosts: all
  vars:
    fish_path: "/usr/bin/fish"
    dest: "{{ ansible_env.HOME }}/.config/fish"

    fisher_url: "https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish"
    omf_url: "https://raw.githubusercontent.com/oh-my-fish/oh-my-fish/master/bin/install"

  tasks:
    - name: "Set fish as shell for user {{ ansible_env.USER }}"
      become: true
      user:
        name: "{{ ansible_env.USER }}"
        shell: "{{ fish_path }}"

    # Oh My Fish
    - name: Downloading oh-my-fish
      get_url:
        url: "{{ omf_url }}"
        dest: /tmp/omf_install
        mode: "0755"
      when: omf_version.rc != 0

    # Fisher
    - name: Create Fish functions directory
      file:
        path: "{{ fisher_install_path | dirname }}"
        state: directory
        mode: "0755"
        owner: "{{ ansible_env.USER }}"
        group: "{{ ansible_env.USER }}"
        recurse: true

    - name: Download fisher.fish script
      get_url:
        url: "{{ fisher_install_url }}"
        dest: "{{ fisher_install_path }}"
        mode: "0644"
        owner: "{{ ansible_env.USER }}"
        group: "{{ ansible_env.USER }}"
      notify: Install Fisher

  handlers:
    - name: Install Fisher
      shell: |
        fish -c "source {{ fisher_install_path }} && {{ fisher_command }}"
      args:
        executable: /usr/bin/fish
      changed_when: false
