---
- name: Installing main packages on Ubuntu
  hosts: all
  become_method: ansible.builtin.sudo

  tasks:
    - name: Install Ansible collections from requirements.yml
      command: "ansible-galaxy collection install -r {{ ansible_env.HOME }}/automation/requirements.yml"
      args:
        creates: "{{ ansible_env.HOME }}/.ansible/collections/ansible_collections"

    - name: Updating apt cache
      become: true
      apt:
        upgrade: true
        update_cache: true

    - name: Installing packages from Ubuntu repository using Nala
      become: true
      package:
        name: "{{ item }}"
        state: present
      loop:
        - curl
        - net-tools
        - unzip
        - yamllint
        - bat # Fancy cat
        - eza # Easy alias
        - nala # Apt package manager
        - xdotool # Keyboard automation
        - fzf # Fuzzy finder
        - pipx # Python package manager
        - python3-pip # Python package manager
        - py

        # Gnome configuration
        - gnome-tweaks # Gnome settings
        - gnome-shell-extensions # Gnome extensions

        # Dev stuff
        - npm
        - nodejs
        - git
        - gitlab-runner

        # System tools
        - rofi # App launcher
        - fish # Shell
        - virtualbox # VM

        # Used by nvim
        - ripgrep # Fancy grep
        - fd-find # Search tool

        # Build from source
        - ninja-build
        - cmake
        - gettext

        # Python
        - portaudio19-dev


    - name: Installing Snap packages
      community.general.snap:
        name: "{{ item }}"
      loop:
        - vlc # Video player
        - multipass # VM manager
        - lxd # Linux containers
        - jump # SSH manager
        - pinta # Image editor
        - localsend # File sharing
        - postman # API calls
        - pinta # Image edtir

    - name: Ensure pipx is in PATH
      command: pipx ensurepath
      become: false
      register: pipx_path_result
      changed_when: pipx_path_result.stdout is not regex('is already in PATH')
