---
- name: Install Qtile using pipx
  hosts: all
  gather_facts: true
  vars:
    pipx_cmd: "/usr/bin/pipx"

  tasks:
    - name: Install Qtile using pipx for the target user
      command: "{{ pipx_cmd }} install qtile"
      args:
        creates: "/home/{{ ansible_env.USER }}/.local/bin/qtile"

    - name: Inject psutil into Qtile using pipx for the target user
      command: "{{ pipx_cmd }} inject qtile psutil"
      register: pipx_inject_result
      changed_when: pipx_inject_result.stdout is not search('injected package')
