---
- name: Installing main packages on Ubuntu
  hosts: all
  become_method: ansible.builtin.sudo
  become: true
  gather_facts: false

  tasks:
    - name: Install Ansible collections from requirements.yml
      command: ansible-galaxy collection install -r requirements.yml
      args:
        creates: ~/.ansible/collections/ansible_collections

    - name: Updating apt cache
      apt:
        upgrade: true
        update_cache: true

    - name: Installing packages from Ubuntu repository using Nala
      package:
        name: "{{ item }}"
        state: present
      loop:
        - curl
        - net-tools
        - unzip
        - yamllint
        - bat # Fancy cat
        - eza # Easy alias
        - nala # Apt package manager
        - xdotool # Keyboard automation
        - yadm # Dotfiles manager
        - fzf # Fuzzy finder

        # Gnome configuration
        - gnome-tweaks # Gnome settings
        - gnome-shell-extensions # Gnome extensions

        # Dev stuff
        - npm # Node package manager
        - nodejs
        - git

        # Used by nvim
        - ripgrep # Fancy grep
        - fd-find # Search tool

        # Build from source
        - ninja-build
        - cmake
        - gettext
      when: nala_installed.stat.exists

    - name: Installing Snap packages
      community.general.snap:
        name: "{{ item }}"
      loop:
        - vlc # Video player
        - multipass # VM manager
        - lxd # Linux containers
        - jump # SSH manager
        - pinta # Image editor
        - localsend # File sharing
